### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported - ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by DavideViolante** [vercel/ncc#1012]
Hello, I'm trying to build [my project](https://github.com/DavideViolante/pr-reviews-reminder-action) with ncc and Node v18 and this error appears. I was able to build as far as I remember with Node v16.

Node.js version: v18.12.1
ncc version: 0.22.3

```
> pr-reviews-reminder-action@2.2.1 build
> ncc build index.js

ncc: Version 0.22.3
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/home/dave/Projects/pr-reviews-reminder-action/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:58216)
    at module.exports (/home/dave/Projects/pr-reviews-reminder-action/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:60642)
    at runCmd (/home/dave/Projects/pr-reviews-reminder-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:47355)
    at 819 (/home/dave/Projects/pr-reviews-reminder-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:44227)
    at __webpack_require__ (/home/dave/Projects/pr-reviews-reminder-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:169)
    at startup (/home/dave/Projects/pr-reviews-reminder-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:339)
    at module.exports.8 (/home/dave/Projects/pr-reviews-reminder-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:371)
    at /home/dave/Projects/pr-reviews-reminder-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:381 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

To temporary fix the error I found on StackOverflow this fix that works:
`export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by DavideViolante** [comment]
Mmh I think I just had the old version of ncc under zeit/ncc instead of vercel/ncc.
