### ISSUE TITLE
Error when using ncc in a Github action

### ISSUE THREAD

**Issue by nicolasfara** [vercel/ncc#1038]
When using `ncc` inside a Github Action, the following error is raised:

```
TypeError: Cannot read properties of undefined (reading 'path')
    at /home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:253938
    at /home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:13:45737
    at /home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:253466
    at /home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1866171
    at finishWithoutResolve (/home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:484092)
    at /home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:484908
    at /home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:485543
    at eval (eval at create (/home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:27:1)
    at /home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:632875
    at /home/nicolas/Documents/opensource-projects/precompute-semantic-release-version-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:631938

Node.js v19.6.0
```

The `ncc` is invoked via `npm run all` which invoke the `ncc build --source-map --license licenses.txt` command.
The repo is here: https://github.com/nicolasfara/precompute-semantic-release-version-action

I have miss configured something or is a problem in `ncc`? I can't figure out anything from that error...

**Comment by mavendonovanhubbard** [comment]
I had the same error message, but I solved it by using 
```
import * as core from "@actions/core";
```
instead of
```
import core from "@actions/core";
```
See [https://stackoverflow.com/questions/65227202/github-actions-how-to-work-with-typescript](https://stackoverflow.com/questions/65227202/github-actions-how-to-work-with-typescript)
