### ISSUE TITLE
Crash from cli-color and node module "d"

### ISSUE THREAD

**Issue by ninja-** [vercel/ncc#594]
```
/tmp/webpack:/x/node_modules/d/index.js:19
		c = contains.call(dscr, "c");
^
TypeError: contains.call is not a function
    at module.exports (/tmp/webpack:/x/node_modules/d/index.js:19:1)
    at Object.86241 (/tmp/webpack:/x/node_modules/cli-color/bare.js:98:1)
    at __webpack_require__ (/tmp/webpack:/x/webpack/bootstrap:20:1)
    at Object.11047 (/tmp/webpack:/x/node_modules/cli-color/index.js:5:1)
    at __webpack_require__ (/tmp/webpack:/x/webpack/bootstrap:20:1)
    at Object.89051 (/tmp/webpack:/x/node_modules/@nestjs/common/services/logger.service.js:6:1)
```

```
The code looks like this:
"use strict";

var isValue         = require("type/value/is")
  , isPlainFunction = require("type/plain-function/is")
  , assign          = require("es5-ext/object/assign")
  , normalizeOpts   = require("es5-ext/object/normalize-options")
  , contains        = require("es5-ext/string/#/contains");

var d = (module.exports = function (dscr, value/*, options*/) {
        var c, e, w, options, desc;
        if (arguments.length < 2 || typeof dscr !== "string") {
                options = value;
                value = dscr;
                dscr = null;
        } else {
                options = arguments[2];
        }
        if (isValue(dscr)) {
                c = contains.call(dscr, "c");
                e = contains.call(dscr, "e");
                w = contains.call(dscr, "w");
        } else {
                c = w = true;
                e = false;
        }

        desc = { value: value, configurable: c, enumerable: e, writable: w };
        return !options ? desc : assign(normalizeOpts(options), desc);
});
```

**Comment by ninja-** [comment]
It looks like ncc is messing up imports and requiring something other in place of `contains`...some other module...

**Comment by ninja-** [comment]
Same issue after upgrading webpack to latest
