### ISSUE TITLE
NodeJS crash

### ISSUE THREAD

**Issue by ninja-** [vercel/ncc#595]
<pre> 1: 0xa3ac30 node::Abort() [/home/user/.nvm/versions/node/v14.5.0/bin/node]
 2: 0xaae1d9  [/home/user/.nvm/versions/node/v14.5.0/bin/node]
 3: 0xc19bab  [/home/user/.nvm/versions/node/v14.5.0/bin/node]
 4: 0xc1b156  [/home/user/.nvm/versions/node/v14.5.0/bin/node]
 5: 0xc1b7d6 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/user/.nvm/versions/node/v14.5.0/bin/node]
 6: 0x13f5159  [/home/user/.nvm/versions/node/v14.5.0/bin/node]
</pre>

I have this meaningless crash when I try to run a simple NestJS-based app - after manually patching bug with cli-color.
There is nothing interesting in the core dump as well, and it doesn't seem to be related to native modules.

Node version: 14.12.0

**Comment by ninja-** [comment]
```
(llnode) v8 bt
 * thread #1: tid = 2924453, 0x00007fe2bd0fe18b libc.so.6`gsignal + 203, name = 'node', stop reason = signal SIGABRT
  * frame #0: 0x00007fe2bd0fe18b libc.so.6`gsignal + 203
    frame #1: 0x00007fe2bd0dd859 libc.so.6`abort + 299
    frame #2: 0x0000000000a3ac41 node`node::Abort() + 33
    frame #3: 0x0000000000aae1d9 node`node::Abort(v8::FunctionCallbackInfo<v8::Value> const&) + 9
    frame #4: 0x0000000000c19bab node`v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 491
    frame #5: 0x0000000000c1b156 node`v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 166
    frame #6: 0x0000000000c1b7d6 node`v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) + 22
    frame #7: 0x00000000013f5159 node`Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
 **   frame #8: 0x000000000138d982 initialize(this=0x1bc24bf40d79:<Object: NestFactoryStatic>, 0x1bc24bf40e91:<function: AppModule at /home/user/IdeaProjects/typescript-starter/dist3/index.js:34692:81>, 0x2c2f018c9ee9:<Object: NestContainer>, 0x2c2f018c8d71:<Object: ApplicationConfig>, 0x2c2f018c7d81:<Object: AbstractHttpAdapter>) at /home/user/IdeaProjects/typescript-starter/dist3/index.js:9836:21 fn=0x000030a07db9b349**
    frame #9: 0x00000000013ba650 (this=0x212240800849:<Global proxy>, 0x2207805c0471:<undefined>) at  fn=0x00002c2f018cd6f1
    frame #10: 0x000000000143660e <stub>
    frame #11: 0x00000000013ad044 <stub>
    frame #12: 0x000000000138b578 <entry>
    frame #13: 0x0000000000ce6cfb node`v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 1883
```

**Comment by ShareQiu1994** [comment]
I have the same problem， My solution now is to return NCC to 0.23.0...   node Vesrion 12.16.0

**Comment by ninja-** [comment]
@ShareQiu1994 I think I solved it, but I don't remember how

**Comment by ryandmello1198** [comment]
> @ShareQiu1994 I think I solved it, but I don't remember how

Why would you that :(
