### ISSUE TITLE
Error while migrating to ncc v0.25.1 

### ISSUE THREAD

**Issue by lionelB** [vercel/ncc#618]
Hello.
We have the following error when migrate from v0.24.1 to v0.25.1 
We use node version v14.3.0
<details>
<summary>error from console</summary>
<pre>
Error: Can't import the named export 'resolve' (imported as 'resolve') from default-exporting module (only default export is available)
Can't import the named export 'statSync' (imported as 'statSync') from default-exporting module (only default export is available)
Can't import the named export 'dirname' (imported as 'dirname') from default-exporting module (only default export is available)
Can't import the named export 'readdirSync' (imported as 'readdirSync') from default-exporting module (only default export is available)
Can't import the named export 'resolve' (imported as 'resolve') from default-exporting module (only default export is available)
Can't import the named export 'dirname' (imported as 'dirname') from default-exporting module (only default export is available)
Can't import the named export 'format' (imported as 'format') from default-exporting module (only default export is available)
Can't import the named export 'normalize' (imported as 'normalize') from default-exporting module (only default export is available)
Can't import the named export 'resolve' (imported as 'resolve') from default-exporting module (only default export is available)
Can't import the named export 'readFileSync' (imported as 'readFileSync') from default-exporting module (only default export is available)
Can't import the named export 'fileURLToPath' (imported as 'fileURLToPath') from default-exporting module (only default export is available)
Can't import the named export 'fileURLToPath' (imported as 'fileURLToPath') from default-exporting module (only default export is available)
Can't import the named export 'notStrictEqual' (imported as 'notStrictEqual') from default-exporting module (only default export is available)
Can't import the named export 'strictEqual' (imported as 'strictEqual') from default-exporting module (only default export is available)
Can't import the named export 'inspect' (imported as 'inspect') from default-exporting module (only default export is available)
Can't import the named export 'basename' (imported as 'basename') from default-exporting module (only default export is available)
Can't import the named export 'dirname' (imported as 'dirname') from default-exporting module (only default export is available)
Can't import the named export 'extname' (imported as 'extname') from default-exporting module (only default export is available)
Can't import the named export 'relative' (imported as 'relative') from default-exporting module (only default export is available)
Can't import the named export 'resolve' (imported as 'resolve') from default-exporting module (only default export is available)
Can't import the named export 'readFileSync' (imported as 'readFileSync') from default-exporting module (only default export is available)
Can't import the named export 'resolve' (imported as 'resolve') from default-exporting module (only default export is available)
Can't import the named export 'readFileSync' (imported as 'readFileSync') from default-exporting module (only default export is available)
Can't import the named export 'writeFile' (imported as 'writeFile') from default-exporting module (only default export is available)
Can't import the named export 'format' (imported as 'format') from default-exporting module (only default export is available)
Can't import the named export 'resolve' (imported as 'resolve') from default-exporting module (only default export is available)
Can't import the named export 'statSync' (imported as 'statSync') from default-exporting module (only default export is available)
    at /Users/lionel/Code/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3258160
    at /Users/lionel/Code/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:2210952
    at eval (eval at create (/Users/lionel/Code/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:1140142), <anonymous>:13:1)
error Command failed with exit code 1.
</pre>
</details>

**Comment by osdevisnot** [comment]
Observing similar error here: https://travis-ci.org/github/osdevisnot/klap/jobs/743571824#L222

**Comment by lionelB** [comment]
hello,

it seems that v0.26.1 fix the problem

**Comment by lionelB** [comment]
I  reopen since with the update of yargs, the problem reappeared

**Comment by vn7n24fzkq** [comment]
I got same error.
