### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by boswelja** [vercel/ncc#635]
Hey there, I'm getting an error when using https://github.com/Ribeiro-Tiago/bundletool
Console output:
```
> aab-info-action@0.1.0 build
> ncc build main.js -m -o dist

ncc: Version 0.26.1
ncc: Compiling file index.js
Error: Module parse failed: Unexpected token (11:21)
File was processed with these loaders:
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/empty-loader.js
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
|   BUNDLETOOL_VERSION,
|   BIN_PATH,
>   __webpack_require__.ab + ".bundletool",
|   __webpack_require__.ab + "bundletool-1.0.0.jar",
| };
    at /mnt/c/Users/boswe/ActionsProjects/aab-info-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3258300
    at /mnt/c/Users/boswe/ActionsProjects/aab-info-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:2210953
    at eval (eval at create (/mnt/c/Users/boswe/ActionsProjects/aab-info-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:1140143), <anonymous>:13:1)
npm ERR! code 1
npm ERR! path /mnt/c/Users/boswe/ActionsProjects/aab-info-action
npm ERR! command failed
npm ERR! command sh -c ncc build main.js -m -o dist

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/boswelja/.npm/_logs/2021-01-01T05_31_14_325Z-debug.log
```
Debug log:
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/mnt/c/Users/boswe/ActionsProjects/aab-info-action/.npmrc Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/boswelja/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session 6b439f8eccd8b7ef
20 timing npm:load Completed in 17ms
21 timing command:run-script Completed in 992ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose pkgid aab-info-action@0.1.0
24 verbose cwd /mnt/c/Users/boswe/ActionsProjects/aab-info-action
25 verbose Linux 4.19.128-microsoft-standard
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
27 verbose node v15.5.0
28 verbose npm  v7.3.0
29 error code 1
30 error path /mnt/c/Users/boswe/ActionsProjects/aab-info-action
31 error command failed
32 error command sh -c ncc build main.js -m -o dist
33 verbose exit 1
```

I'm importing node-aab-parser, but have tried only using it's bundletool dependency and I get the same error.
Source code here in case it's an issue with my code: https://github.com/boswelja/aab-info-action

**Comment by boswelja** [comment]
Update: The issue seems to be with ncc not being able to handle the bundletool jar.

**Comment by boswelja** [comment]
I worked around this by downloading the jar as needed instead of trying to bundle it with releases
