### ISSUE TITLE
Can't import the named export... (only default export is available)

### ISSUE THREAD

**Issue by dwkfcml** [vercel/ncc#639]
Hello,
When I use `ncc build index.js`, the following problem appears：

ncc: Version 0.26.2
ncc: Compiling file index.js
Error: Can't import the named export 'Assignment'.'StatusChange' (imported as 'Assignment') from default-exporting module (only default export is available)
Can't import the named export 'Unit'.'Factory'.'newInstance' (imported as 'Unit') from default-exporting module (only default export is available)
Can't import the named export 'Unit'.'sync' (imported as 'Unit') from default-exporting module (only default export is available)
Can't import the named export 'Unit'.'mount' (imported as 'Unit') from default-exporting module (only default export is available)
Can't import the named export 'Batch'.'lazyLoadSampleBatch' (imported as 'Batch') from default-exporting module (only default export is available)
Can't import the named export 'Batch'.'Factory'.'newInstance' (imported as 'Batch') from default-exporting module (only default export is available)
...

Module parse failed: Unexpected token (1:5)
File was processed with these loaders:
 * ../../local/lib/node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
> FROM alpine
| RUN apk add --no-cache apache2 php7-apache2 php7-json php7-iconv php7-mbstring php7-ctype php7-opcache php7-openssl \
|     && sed -i -e "/^<Directory \"\/var\/www\/localhost\/htdocs\">$/,/^<\/Directory>$/d" /etc/apache2/httpd.conf \
Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ../../local/lib/node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
> <?php
| 
| $body = file_get_contents('php://input');
    at /usr/local/lib/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3258300
    at /usr/local/lib/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:2210953
    at eval (eval at create (/usr/local/lib/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:1140143), <anonymous>:13:1)

Why is this and what should i do? thanks

**Comment by vn7n24fzkq** [comment]
Seems a duplicate of #618
