### ISSUE TITLE
dist contains whole typescript lib

### ISSUE THREAD

**Issue by ywwhack** [vercel/ncc#642]
When I use `ncc build`, the output contains all typescript/lib, such as below:
![image](https://user-images.githubusercontent.com/8746197/104321564-c2c4f680-551e-11eb-8764-09ea6981d489.png)

I try to comment a require statement like `require(someConfigPath)`，it then no longer output typescript/lib. It seems like import a module using "require" has some problems. 

Is there any workaround to use "require" and the dist dir not contains the whole typescript/lib ?

**Comment by cobraz** [comment]
I have the same problem. Is there a way to ignore the package?

**Comment by Songkeys** [comment]
append `-e typescript`

**Comment by cobraz** [comment]
@Songkeys This excludes `typescript` but from what I understand, it's because one of @ywwhack packages or the code depends on `typescript`. This in turns means that we'll get `Error: Cannot find module 'typescript'`

**Comment by Songkeys** [comment]
@cobraz I think the production environment should not need any help from the `typescript` lib. Why would you need type checking / generating on the production env? You can avoid using it with a conditional requiring if you are requiring but not actually using it:

```javascript
const typescript = process.env.NODE_ENV === 'production' ? {} : require('typescript')
```

**Comment by cobraz** [comment]
@Songkeys You can see specifically what it is used for in pulumi/action#50. It's actually a Github Actions I'm trying to compile into one file. Commiting 400+ Typescript files feels wrong, and actually, the underlying package `@pulumi/pulumi` uses `typescript` in the runtime parts. (e.g. https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/closure/utils.ts).

I don't know yet if I actually need `typescript` there, or if I can dirty patch it. We'll see :)

If you have any other ideas/approaches; I'd love some feedback!

**Comment by Remirror-zz** [comment]
Funny enough, I currently face the opposite problem: I do need `typescript` to be included in the file generated by `ncc` in order to transpile some user-written TS-code, but whenever I try to use `ncc` on even the simplest script such as
```
    import * as ts from 'typescript';
    eval(ts.transpile('const x: number = 5; console.log(x);'));
```
I get the following error:
_ncc: Compiling file typescript/lib/tsserver.js
Error: Conflict: Multiple assets emit different content to the same filename typescript/lib/tsserver.js
    at C:\Users\abc\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:1:3258429
    at C:\Users\abc\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:1:2210953
    at eval (eval at create (C:\Users\abc\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:1:1140143), <anonymous>:13:1)_

**Comment by EvanBoyle** [comment]
> If one of your dependencies is requiring typescript, you can have a dirty patch on the generated code:

@Songkeys would it be possible to enable this via an `ncc build` flag? I _think_ this would be similar to webpack's exclude: https://webpack.js.org/configuration/module/#ruleexclude

Then rather than applying a patch, a similar outcome could be achieved with a single command `ncc build index.ts -e typescript --exclude typescript`

**Comment by Songkeys** [comment]
> would it be possible to enable this via an `ncc build` flag?

@EvanBoyle It would be much convenient if we have one. I believe many unused dependencies (like `typescript` here) are still `require`-ing on top level of a file in production environment, which may cause errors because we've `--exclude`d them when bundling.

But I'm not sure if such a flag is *generally* reasonable and applicable. But you can patch it yourself anyway.

@guybedford @styfle What do you think? Should we provide something like `ncc build index.ts --drop typescript` to *completely* remove a package by applying a patch as follows?

```js
let content = fs.readFileSync('index.js', "utf-8");
content = content.replace(/require\("typescript"\)/g, "{}")
fs.writeFileSync('index.js', content)
```

**Comment by styfle** [comment]
You can't replace like that.

Imagine existing code:

```js
const typescript = require('typescript')
const result = typescript.compiler.transform('file.ts')
```

If you replaced it with your solution then it would fail at runtime because there would be missing properties:

```js
const typescript = {}
const result = typescript.compiler.transform('file.ts')
```

-----

The correct solution is to use `ncc build index.js -e typescript` or the longer form `--external` as [mentioned above](https://github.com/vercel/ncc/issues/642#issuecomment-769571604).

See the docs here: https://github.com/vercel/ncc#options

**Comment by Songkeys** [comment]
> If you replaced it with your solution then it would fail at runtime because there would be missing properties

I knew. It works only when we are certain that it won't break our production code. I.e. we are sure that the code containing missing properties will never run in production environment.

But yes. It's not *generally* a correct solution.

**Comment by EvanBoyle** [comment]
> The correct solution is to use ncc build index.js -e typescript or the longer form --external as mentioned above.

@styfle this leaves a top level `require("typescript")` in the code. that statement alone fails at runtime. For our app we know that:

1. typescript is not required
3. removing the `require("typescript") with [the patch here](https://github.com/vercel/ncc/issues/642#issuecomment-853736756) does not cause a runtime failure 

I would describe it as "manual tree shaking". As a user I know that this dependency is not needed for the specific app I am building, but the compiler won't drop it, and the exclude flag doesn't help because the top level require gets left in the resulting code. 

I understand that I can accomplish this with a patch on the generated code, but this another manual step I have to maintain. Seems very similar to https://webpack.js.org/configuration/module/#ruleexclude which has first class support in webpack. 

I also understand that this flag would not be conservatively correct, and would rely on judgement of users to use appropriately.

**Comment by styfle** [comment]
ncc is built on webpack so feel free to submit a PR with a test if you want to add this feature 👍
