### ISSUE TITLE
Error in path when running in Windows

### ISSUE THREAD

**Issue by LuisEnMarroquin** [vercel/ncc#670]
I want to run the package but it throws an error

```shell
$ ncc build src/scripts.ts --out public --minify
ncc: Version 0.27.0
ncc: Compiling file index.js
Error: Module build failed (from C:\Users\Chimney\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc\loaders\ts-loader.js):
Error: Could not load TypeScript compiler with NPM package name `C:\Users\Chimney\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc/typescript.js`. Are you sure it is correctly installed?
    at Object.loader (C:\Users\Chimney\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc\loaders/ts-loader.js.cache.js:1:352078)
    at compiler.close.n (C:\Users\Chimney\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:1:3258429)
    at C:\Users\Chimney\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:1:2210953
    at _promise0.then._result0 (eval at create (C:\Users\Chimney\AppData\Roaming\npm\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:1:1140143), <anonymous>:13:1)
```

The problem probably is that paths in Windows are not correcly concatenated

![image](https://user-images.githubusercontent.com/35376824/111884773-52f14300-8989-11eb-9794-53edde3f5ea1.png)

Searching the code in found out that in `src/index.js` (line ~300) paths are created using `eval`

```shell
compiler: eval('__dirname + "/typescript.js"')
```

A possible solution may be to use `join` function from `Path`

```shell
compiler: join(__dirname, "typescript.js")
```

Or if eval is necesary this option may work

```shell
compiler: eval('join(__dirname, "typescript.js")'),
```

Also, how can I run the project locally? I tried with:

```shell
yarn
yarn build
npm install -g .
cd ../otherProjectFolder/
ncc build src/server.ts --out dist --target es2020 --minify
```

But I get this error

![image](https://user-images.githubusercontent.com/35376824/111884992-aa43e300-898a-11eb-973d-aad01e0266a8.png)

**Comment by LuisEnMarroquin** [comment]
I figured out that this was due because `typescript` wasn't installed globally
