### ISSUE TITLE
source-map: MemoryFileSystemError: ENOENT: no such file or directory, readFile '/index.js.map'

### ISSUE THREAD

**Issue by aminya** [vercel/ncc#711]
When I use `ncc` with `--source-map` I get this error:

```js
> ncc build --minify --source-map

ncc: Version 0.28.6
ncc: Compiling file index.js
MemoryFileSystemError: ENOENT: no such file or directory, readFile '/index.js.map'
    at MemoryFileSystem.readFileSync (C:\aminya\setup-ninja\node_modules\.pnpm\@vercel+ncc@0.28.6\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:1:886504)
    at finalizeHandler (C:\aminya\setup-ninja\node_modules\.pnpm\@vercel+ncc@0.28.6\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:37:1822579) {
  code: 'ENOENT',
  errno: 34,
  path: '/index.js.map',
  operation: 'readFile'
}
```

Reproducible on:
https://github.com/aminya/setup-ninja/tree/update

**Comment by styfle** [comment]
I see a different error

```
ERROR in /var/task/setup-ninja/src/main.ts(23,23)
TS2792: Cannot find module '@actions/core'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
```

Once I added `"moduleResolution": "node"` to tsconfig.json, it worked

```
ncc build src/main.ts --source-map --minify
```
