### ISSUE TITLE
Can not parse arrow function with the arrow symbol in the next line

### ISSUE THREAD

**Issue by wclr** [vercel/ncc#721]
Such code for input:
```js
fn = (
    
)
  => {
    
};

```
Is not compiling with the error:
```
ncc: Version 0.28.6
ncc: Compiling file index.js
Error: Module parse failed: Unexpected token (4:0)
File was processed with these loaders:
 * ./node_modules/.pnpm/@vercel/ncc@0.28.6/node_modules/@vercel/ncc/dist/ncc/loaders/empty-loader.js
 * ./node_modules/.pnpm/@vercel/ncc@0.28.6/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js
 * ./node_modules/.pnpm/@vercel/ncc@0.28.6/node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
| exports._deleteMany = (
|
> )
|   => {
|
```

Such code is generated automatically by the tolling I use (Purescript compiler), though it is strange, it is still legal JS.

**Comment by styfle** [comment]
That code is not valid. Here's what Node.js 14 says:

```
$ node example.js

example.js:4
  => {
  ^^

SyntaxError: Unexpected token '=>'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Simran-B** [comment]
Yeah, the [specification](https://262.ecma-international.org/11.0/#sec-arrow-function-definitions) doesn't leave any room for interpretation:

> ### 14.2 Arrow Function Definitions Syntax
> ArrowFunction [In, Yield, Await]:
> ArrowParameters [?Yield, ?Await] **[no LineTerminator here]** => ConciseBody …
