### ISSUE TITLE
Error when mixing ESM and CJS

### ISSUE THREAD

**Issue by joeldenning** [vercel/ncc#749]
In a project with `"type": "module"` in the package.json that also contains `.cjs` files, the `.cjs` files cannot access the global variables `__filename`, `__dirname`, etc that should be available to commonjs files.

I've created https://github.com/joeldenning/ncc-mixed-modules to demonstrate the problem.

```sh
~/c/ncc-mixed-modules (main|✔) $ node dist/index.js
file:///Users/joeldenning/code/ncc-mixed-modules/dist/index.js:6
console.log("dep.cjs executing", __filename)
                                 ^

ReferenceError: __filename is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/joeldenning/code/ncc-mixed-modules/dist/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at Object.135 (file:///Users/joeldenning/code/ncc-mixed-modules/dist/index.js:6:34)
    at __nccwpck_require__ (file:///Users/joeldenning/code/ncc-mixed-modules/dist/index.js:32:41)
    at file:///Users/joeldenning/code/ncc-mixed-modules/dist/index.js:52:66
    at file:///Users/joeldenning/code/ncc-mixed-modules/dist/index.js:56:3
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

**Comment by guybedford** [comment]
This would be a Webpack semantic in how webpack builds CommonJS.

One of the things to note is that `__filename` in a bundle is not well-defined because many files with many different `__filename` values bundled together into a final bundle will be in a bundle file that has another `__filename` value. So then the question is which one of those `__filename` values should be used. I don't think any bundlers have a good answer to this from a definition perspective yet. Browserify used to use `/local/path.js` as cwd-relative turning into absolute-url-relative paths, but I'm not sure if Webpack fully adopted that convention (//cc @sokra).

So a question to understand further would be - what is the use case you have in mind here that you're looking to handle? Then we can discuss ways to approach that use case rather.

**Comment by joeldenning** [comment]
In my case, I worked around it by replacing `__filename` with `process.cwd()`. The __filename was there because it was part of a generated file, and it was used as part of `path.resolve(__filename, 'some-other-file.js')`.

**Comment by guybedford** [comment]
Was the generated file an ES module or a CJS module?

**Comment by joeldenning** [comment]
The generated file was a CJS module - it was created by sequelize-cli as part of creating a database migration. For reference, here's the original file generated by sequelize-cli:

https://github.com/JustUtahCoders/flax-crm/blob/5c35bbe3f8818ea4f936fbef09fe85c0367b98ca/backend/DB/models/index.cjs

**Comment by appelgriebsch** [comment]
Looks like it also mixes up import and require statements in the bundled mjs:

![screenshot-2021-10-06-162911](https://user-images.githubusercontent.com/6803419/136224898-13d5dfca-67af-4db6-9ca8-e58c50ba8438.png)

As such its not possible to build with the current version. The version 0.28.x builds it just fine though (only cjs output).

**Comment by algo7** [comment]
any news on this?

**Comment by styfle** [comment]
It looks like https://github.com/webpack/webpack/issues/14072 was finally merged and released in `webpack@5.90.0`.

The PR to upgrade webpack (https://github.com/vercel/ncc/pull/1158) is currently failing CI so if anyone wants to fix it, I can take a look, thanks!

**Comment by RSS1102** [comment]
> It looks like [webpack/webpack#14072](https://github.com/webpack/webpack/issues/14072) was finally merged and released in `webpack@5.90.0`.
> 
> The PR to upgrade webpack (#1158) is currently failing CI so if anyone wants to fix it, I can take a look, thanks!

transfer to  https://github.com/vercel/ncc/pull/1177

**Comment by gentlementlegen** [comment]
This issue still seems relevant. `__dirname` is still in the output code even though the produced code should be ESM, causing the runtime to crash with `ReferenceError: __dirname is not defined`.

**Comment by JessicaSachs** [comment]
FYI there's an issue open on GitHub Action's official template where `@vercel/ncc` is not the recommended tool _because_ of this `__filename`/`__dirname` issue.

Rollup is being recommended as the alternative. This Rollup plugin is what solves the `__filename` issue https://github.com/calvinmetcalf/rollup-plugin-node-globals  - any chance we can implement something similar to this rollup plugin?

Quirky webpack-isms and lack of standards around imports have always been difficult for authors to work with, but I feel like solving this in-repo is possible. NCC has been awesome otherwise.

https://github.com/actions/typescript-action/issues/1050#issuecomment-2998329711
