### ISSUE TITLE
Error: ES Modules may not assign module.exports or exports.*

### ISSUE THREAD

**Issue by narkeeso** [vercel/ncc#755]
I'm getting the following error when running my compiled ncc `v0.3.6` package:

```
Error: ES Modules may not assign module.exports or exports.*
```

```
> node dist/index.js

/tmp/webpack:/@tract/api/webpack/runtime/harmony module decorator:7
                        throw new Error('ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ' + module.id);
^
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 7113
    at Object.set [as exports] (/tmp/webpack:/@tract/api/webpack/runtime/harmony module decorator:7:1)
    at Module.7113 (/tmp/webpack:/@tract/api/src/index.ts:49:1)
    at __nccwpck_require__ (/tmp/webpack:/@tract/api/webpack/bootstrap:21:1)
    at /tmp/webpack:/@tract/api/webpack/startup:4:1
    at Object.<anonymous> (/tmp/de9154a039b5ea16efa4dd1daae4f0d7/index.js:382913:12)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
```

```
// tsconfig.json
{
  "ts-node": {
    // these options are overrides used only by ts-node
    // same as our --compilerOptions flag and our TS_NODE_COMPILER_OPTIONS environment variable
    "compilerOptions": {
      "module": "commonjs"
    }
  },
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "module": "ES2020",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "rootDir": "./src",
    "outDir": "lib",
    "skipLibCheck": true,
    "strict": true,
    "target": "es2020",
    "lib": ["ES2020"],
    "esModuleInterop": true,
    "typeRoots": ["./src/@types", "./node_modules/@types"]
  },
  "compileOnSave": true,
  "include": ["./src"]
}
```

```
// package.json
{
  "name": "@tract/api",
  "version": "0.0.1",
  "description": "Tract Web API",
  "main": "lib/index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "tsc",
    "build:docker": "ncc build src/index.ts",
    "start": "tsnd --respawn src/index.ts",
    "start:prod": "node lib/index.js"
  },
  "engine": {
    "node": 14
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@api.video/nodejs-client": "^2.0.6",
    "@google-cloud/pubsub": "^2.16.3",
    "@sendgrid/mail": "^7.4.5",
    "@tract/common": "*",
    "axios": "^0.21.1",
    "dotenv": "^10.0.0",
    "fastify": "^3.17.0",
    "fastify-cors": "^6.0.1",
    "firebase-admin": "^9.9.0",
    "getstream": "^7.2.10",
    "jsonwebtoken": "^8.5.1",
    "mime-types": "^2.1.31",
    "stream-chat": "^3.11.0"
  },
  "devDependencies": {
    "ts-node-dev": "^1.1.6",
    "typescript": "^4.3.2",
    "@types/mime-types": "^2.1.0",
    "@types/node": "^15.12.2"
  }
}
```

```
// ncc build output
ncc: Version 0.29.2
ncc: Compiling file index.js into ESM
ncc: Using typescript@4.3.5 (local user-provided)
ncc: Version 0.29.2
ncc: Compiling file client/faye-browser-min.js into CJS
ncc: Version 0.29.2
ncc: Compiling file client/faye-browser.js into CJS
ncc: Version 0.29.2
ncc: Compiling file protos/http.js into CJS
ncc: Version 0.29.2
ncc: Compiling file protos/locations.js into CJS
ncc: Version 0.29.2
ncc: Compiling file protos/iam_service.js into CJS
ncc: Version 0.29.2
ncc: Compiling file protos/operations.js into CJS
    0kB  protos/google/protobuf/compiler/ruby/ruby_generated_pkg_implicit.proto
    0kB  protos/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy.proto
    0kB  protos/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit.proto
    1kB  protos/google/type/month.proto
    1kB  protos/google/type/localized_text.proto
    1kB  protos/google/type/latlng.proto
    1kB  protos/google/type/fraction.proto
    1kB  protos/google/type/dayofweek.proto
    1kB  protos/google/monitoring/v3/mutation_record.proto
    1kB  protos/google/iam/v1/options.proto
    1kB  protos/google/iam/v1/logging/audit_data.proto
    1kB  protos/google/api/source_info.proto
    1kB  protos/google/api/label.proto
    1kB  protos/google/api/control.proto
    1kB  protos/google/api/annotations.proto
    2kB  protos/google/type/timeofday.proto
    2kB  protos/google/type/money.proto
    2kB  protos/google/type/interval.proto
    2kB  protos/google/type/date.proto
    2kB  protos/google/type/calendar_period.proto
    2kB  protos/google/rpc/status.proto
    2kB  protos/google/protobuf/source_context.proto
    2kB  protos/google/protobuf/empty.proto
    2kB  protos/google/protobuf/compiler/ruby/ruby_generated_code.proto
    2kB  protos/google/protobuf/compiler/ruby/ruby_generated_code_proto2.proto
    2kB  protos/google/monitoring/v3/span_context.proto
    2kB  protos/google/monitoring/v3/dropped_labels.proto
    2kB  protos/google/api/log.proto
    2kB  protos/google/api/expr/v1beta1/source.proto
    2kB  protos/google/api/expr/v1beta1/decl.proto
    2kB  protos/google/api/expr/v1alpha1/explain.proto
    3kB  protos/google/type/expr.proto
    3kB  protos/google/protobuf/util/json_format.proto
    3kB  protos/google/logging/type/log_severity.proto
    3kB  protos/google/cloud/location/locations.proto
    3kB  protos/google/api/system_parameter.proto
    3kB  protos/google/api/usage.proto
    3kB  protos/google/api/logging.proto
    3kB  protos/google/api/launch_stage.proto
    3kB  protos/google/api/servicecontrol/v1/http_request.proto
    3kB  protos/google/api/servicecontrol/v1/metric_value.proto
    3kB  protos/google/api/httpbody.proto
    3kB  protos/google/api/field_behavior.proto
    3kB  protos/google/api/context.proto
    3kB  protos/google/api/consumer.proto
    3kB  protos/google/api/config_change.proto
    3kB  protos/google/api/client.proto
    3kB  protos/google/api/billing.proto
    3kB  protos/google/api/endpoint.proto
    3kB  protos/google/api/expr/v1beta1/value.proto
    3kB  protos/google/api/expr/v1alpha1/value.proto
    4kB  protos/google/type/quaternion.proto
    4kB  protos/google/type/datetime.proto
    4kB  protos/google/protobuf/wrappers.proto
    4kB  protos/google/protobuf/struct.proto
    4kB  protos/google/monitoring/v3/group.proto
    4kB  protos/google/logging/type/http_request.proto
    4kB  protos/google/api/monitoring.proto
    4kB  protos/google/api/servicecontrol/v1/check_error.proto
    4kB  protos/google/api/expr/v1beta1/eval.proto
    4kB  protos/google/api/expr/v1alpha1/eval.proto
    5kB  protos/google/type/phone_number.proto
    5kB  protos/google/protobuf/duration.proto
    5kB  protos/google/iam/v1/iam_policy.proto
    5kB  protos/google/api/monitored_resource.proto
    5kB  protos/google/api/servicecontrol/v1/operation.proto
    5kB  protos/google/api/servicecontrol/v1/log_entry.proto
    5kB  protos/google/api/expr/v1alpha1/conformance_service.proto
    6kB  protos/status.json
    6kB  protos/google/type/postal_address.proto
    6kB  protos/google/type/color.proto
    6kB  protos/google/protobuf/type.proto
    6kB  protos/google/protobuf/timestamp.proto
    6kB  protos/google/protobuf/any.proto
    6kB  protos/google/protobuf/util/json_format_proto3.proto
    6kB  protos/google/api/service.proto
    6kB  protos/google/api/documentation.proto
    6kB  package.json
    7kB  protos/google/rpc/code.proto
    7kB  protos/google/api/quota.proto
    7kB  protos/google/api/servicecontrol/v1/distribution.proto
    7kB  protos/google/api/backend.proto
    8kB  protos/google/protobuf/api.proto
    8kB  protos/google/protobuf/field_mask.proto
    8kB  protos/google/iam/v1/policy.proto
    8kB  protos/google/api/distribution.proto
    9kB  protos/google/rpc/error_details.proto
    9kB  protos/google/protobuf/compiler/plugin.proto
    9kB  protos/google/monitoring/v3/notification.proto
    9kB  protos/google/monitoring/v3/alert_service.proto
    9kB  protos/google/monitoring/v3/metric.proto
    9kB  protos/google/api/auth.proto
    9kB  protos/google/api/expr/v1beta1/expr.proto
   10kB  protos/google/longrunning/operations.proto
   10kB  protos/google/monitoring/v3/uptime_service.proto
   10kB  protos/google/monitoring/v3/group_service.proto
   10kB  protos/google/api/servicemanagement/v1/resources.proto
   10kB  protos/google/api/metric.proto
   10kB  protos/google/api/servicecontrol/v1/quota_controller.proto
   10kB  protos/google/api/servicecontrol/v1/service_controller.proto
   11kB  protos/google/api/resource.proto
   11kB  protos/google/api/expr/v1alpha1/syntax.proto
   11kB  protos/google/api/expr/v1alpha1/checked.proto
   12kB  protos/google/rpc/context/attribute_context.proto
   13kB  protos/google/monitoring/v3/service_service.proto
   14kB  protos/http.d.ts
   15kB  protos/google/api/http.proto
   16kB  protos/google/monitoring/v3/uptime.proto
   17kB  protos/google/monitoring/v3/service.proto
   17kB  protos/google/monitoring/v3/notification_service.proto
   17kB  protos/google/monitoring/v3/alert.proto
   18kB  protos/google/monitoring/v3/metric_service.proto
   22kB  protos/google/monitoring/v3/common.proto
   22kB  protos/google/api/servicemanagement/v1/servicemanager.proto
   33kB  protos/locations.json
   37kB  protos/operations.json
   37kB  protos/google/protobuf/descriptor.proto
   38kB  client/faye-browser-min.js
   40kB  sourcemap-register.js
   41kB  protos/iam_service.json
  103kB  client/faye-browser.js
  105kB  client/faye-browser.js.map
  124kB  protos/http.js
  136kB  client/faye-browser-min.js.map
  178kB  protos/locations.d.ts
  209kB  protos/operations.d.ts
  222kB  protos/iam_service.d.ts
  661kB  protos/locations.js
  734kB  protos/operations.js
  792kB  protos/iam_service.js
14920kB  index.js
16406kB  index.js.map
19058kB  [22583ms] - ncc 0.29.2
```

Do I have something misconfigured?

**Comment by styfle** [comment]
Since you're using `"type": "module"`, ncc is going to emit ESM.

The error sounds like some of your code (or dependencies) is not ESM since its assigning `module.exports`.

**Comment by narkeeso** [comment]
I've tried compiling without type: module and get the same error. I guess a dependency might be an issue? Is there a way to make the dependencies compatible?

**Comment by narkeeso** [comment]
I figured it out, I had some module.exports code from an example I pulled from fastify. Converted it and removed `"type": "module"`. Everything seems to be working great.
