### ISSUE TITLE
BigInt issue compiling "hexy"

### ISSUE THREAD

**Issue by erossignon** [vercel/ncc#828]
```
npm install hexy
````

```
// index.js
require("hexy")
```

```
$ ncc build index.js
```

```
ncc: Version 0.28.3
ncc: Compiling file index.js
node:31420) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at Object.BinaryExpression (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:106204)
    at walk (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:102648)
    at Object.BinaryExpression (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:103162)
    at walk (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:102648)
    at e.exports (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:102544)
    at computePureStaticValue (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:79575)
    at Object.enter (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:86921)
    at visit (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:1:149371)
    at visit (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:1:149661)
    at visit (/home/etienne/pnpm-global/5/node_modules/.pnpm/@vercel+ncc@0.28.3/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:1:149619)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

see also https://github.com/a2800276/hexy.js/issues/20

**Comment by erossignon** [comment]
fixed the issue by submitting a PR to the hexy repo.
