### ISSUE TITLE
Module xyz has no exported member 

### ISSUE THREAD

**Issue by Dexus** [vercel/ncc#853]
```
yarn run v1.22.17
$ ncc build -m -d -s src/pem.ts -o dist
ncc: Version 0.33.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@4.5.5 (local user-provided)
Error: Module build failed (from ./node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js):
Error: TypeScript emitted no output for /home/jfroehle/Documents/github/dexus/pem/src/pem.ts.
    at makeSourceMapAndFinish (/home/jfroehle/Documents/github/dexus/pem/node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js.cache.js:13:224695)
    at successLoader (/home/jfroehle/Documents/github/dexus/pem/node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js.cache.js:13:224107)
    at Object.loader (/home/jfroehle/Documents/github/dexus/pem/node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js.cache.js:13:223585)
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/interfaces.ts(1,14)
      TS2305: Module '"./types"' has no exported member 'Code'.
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/interfaces.ts(1,20)
      TS2305: Module '"./types"' has no exported member 'ErrNull'.
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/interfaces.ts(1,29)
      TS2305: Module '"./types"' has no exported member 'StdOutErr'.
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/openssl.ts(3,9)
      TS2305: Module '"./interfaces"' has no exported member 'CallbackErrCodeStdoutSdrerr'.
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/openssl.ts(3,38)
      TS2305: Module '"./interfaces"' has no exported member 'CallbackErrStdout'.
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/openssl.ts(3,57)
      TS2305: Module '"./interfaces"' has no exported member 'CallbackErr'.
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/openssl.ts(4,14)
      TS2305: Module '"./types"' has no exported member 'Code'.
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/openssl.ts(4,20)
      TS2305: Module '"./types"' has no exported member 'ErrNull'.
[tsl] ERROR in /home/jfroehle/Documents/github/dexus/pem/src/openssl.ts(4,29)
      TS2305: Module '"./types"' has no exported member 'StdOutErr'.
    at /home/jfroehle/Documents/github/dexus/pem/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1896993
    at /home/jfroehle/Documents/github/dexus/pem/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:353322
    at _done (eval at create (/home/jfroehle/Documents/github/dexus/pem/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:117937), <anonymous>:9:1)
    at eval (eval at create (/home/jfroehle/Documents/github/dexus/pem/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:117937), <anonymous>:34:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

interfaces.ts:
```ts
import type {Code, ErrNull, StdOutErr } from './types'

export interface CallbackErrCodeStdoutSdrerr {
    (err: ErrNull, code?: Code, stdout?: StdOutErr, stderr?: StdOutErr): void;
}

export interface CallbackErrStdout {
    (err: ErrNull, stdout?: StdOutErr): void;
}

export interface CallbackErr {
    (err: ErrNull): void;
}
```

types.ts:
```ts
export type ErrNull = Error | null
export type Code = number | string | null | undefined
export type StdOutErr = string | NodeJS.ArrayBufferView
```

a normal run on `tsc` works

**Comment by Dexus** [comment]
Solved you should create output and not emit stuff
