### ISSUE TITLE
[0.33.2 regression] Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by C0ZEN** [vercel/ncc#869]
When building my app with the latest version [0.33.2](https://github.com/vercel/ncc/releases/tag/0.33.2), I have this error during the build: `Cannot read property 'name' of undefined`.
Everything was OK with the [0.33.1](https://github.com/vercel/ncc/releases/tag/0.33.1).
The script used is `ncc build --license licenses.txt --minify`.

**StackTrace:**

```
ncc: Version 0.33.2
ncc: Compiling file index.js into CJS
ncc: Using typescript@4.5.5 (local user-provided)
HookWebpackError: Cannot read property 'name' of undefined
    at makeWebpackError (S:\C0ZEN\Documents\sonia\stale\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:37:374401)
    at S:\C0ZEN\Documents\sonia\stale\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:37:177732
    at eval (eval at create (S:\C0ZEN\Documents\sonia\stale\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:20:107860), <anonymous>:13:1)
    at fn (S:\C0ZEN\Documents\sonia\stale\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:37:140906)
    at _next0 (eval at create (S:\C0ZEN\Documents\sonia\stale\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:20:107860), <anonymous>:11:1)
    at eval (eval at create (S:\C0ZEN\Documents\sonia\stale\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:20:107860), <anonymous>:26:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This is visible on this public repository: https://github.com/Sonia-corporation/stale/pull/466

**Comment by crs-k** [comment]
I am having the same issue with moving from from `0.33.1` to `0.33.2`

Public repo: https://github.com/crs-k/stale-branches/pull/257

Adding some detail since my script is slightly different:
`ncc build --source-map --license licenses.txt`

> typescript-action@0.0.0 package
> set NODE_OPTIONS=--openssl-legacy-provider && ncc build --source-map --license licenses.txt

```
ncc: Version 0.33.2
ncc: Compiling file index.js into CJS
HookWebpackError: Cannot read properties of undefined (reading 'name')
    at makeWebpackError (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:374401)
    at /home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:177732
    at eval (eval at create (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:107860), <anonymous>:13:1)
    at fn (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:140906)
    at _next1 (eval at create (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:107860), <anonymous>:11:1)
    at eval (eval at create (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:107860), <anonymous>:27:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'name')
    at PluginChunkReadHandler.extractIdentifiedModule (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:602615)
    at /home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:602222
    at WebpackInnerModuleIterator.internalCallback (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:622425)
    at WebpackInnerModuleIterator.iterateModules (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:622056)
    at /home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:602184
    at WebpackChunkModuleIterator.iterateModules (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:614534)
    at PluginChunkReadHandler.processChunk (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:602128)
    at _loop_1 (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:618468)
    at WebpackCompilerHandler.iterateChunks (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:619131)
    at /home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:616874
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read properties of undefined (reading 'name')
    at PluginChunkReadHandler.extractIdentifiedModule (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:602615)
    at /home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:602222
    at WebpackInnerModuleIterator.internalCallback (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:622425)
    at WebpackInnerModuleIterator.iterateModules (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:622056)
    at /home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:602184
    at WebpackChunkModuleIterator.iterateModules (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:614534)
    at PluginChunkReadHandler.processChunk (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:602128)
    at _loop_1 (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:618468)
    at WebpackCompilerHandler.iterateChunks (/home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:619131)
    at /home/runner/work/stale-branches/stale-branches/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:616874
```

**Comment by C0ZEN** [comment]
Workaround: removing the flag `--license` makes the build pass.
