### ISSUE TITLE
Puppeteer support, problem with require.resolve

### ISSUE THREAD

**Issue by BCaspari** [vercel/ncc#874]
Using ncc with puppeteer@13.2.2 does not work. The exception thrown is: 
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number (49654)
    at validateString (internal/validators.js:124:11)
    at dirname (path.js:645:5)`

puppeteer@13.2.1 worked, the PR that broke it is https://github.com/puppeteer/puppeteer/pull/8003

The problem is the following line in the puppeteer code
`const puppeteerRootDirectory = sync(
    dirname(require.resolve('./initialize-node'))
  );`
which is transformed into
`const puppeteerRootDirectory = (0, pkg_dir_1.sync)((0, path_1.dirname)(/*require.resolve*/(49654)));`

I think require.resolve should not be replaced with number, but a string here?

**Comment by louisgv** [comment]
Yup, having the exact issue. I wonder where in ncc does the require statement transformed the path to a number?

**Comment by louisgv** [comment]
Hmm... I downgraded to puppeteer@13.2.1 and the problem still exists.

**Comment by BCaspari** [comment]
puppeteer@13.2.1 works for us... Which error do you get? Because the line I mentioned above was added in 13.2.2.
