### ISSUE TITLE
using baseUrl: "." causes json files in node_modules to be omitted from build result.

### ISSUE THREAD

**Issue by charlesdeuter** [vercel/ncc#891]
Hi!

I am seeing an issue when using the `baseUrl: "."` option in my tsconfig.

It is causing the rollbar library to throw the error seen below

```
TypeError: Cannot read properties of undefined (reading 'server')
    at Object.call (/Users/charlie-work/repos/bug-example-ncc/build/webpack:/bug-example-ncc/node_modules/rollbar/src/server/rollbar.js:662:1)
    at __nccwpck_require__ (/Users/charlie-work/repos/bug-example-ncc/build/webpack:/bug-example-ncc/webpack/bootstrap:21:1)
    at /Users/charlie-work/repos/bug-example-ncc/build/webpack:/bug-example-ncc/webpack/runtime/compat:2:1
    at /Users/charlie-work/repos/bug-example-ncc/build/webpack:/bug-example-ncc/src/main.ts:10:1
    at Object.<anonymous> (/Users/charlie-work/repos/bug-example-ncc/build/webpack:/bug-example-ncc/src/main.ts:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
```

The server variable is an imported from the `package.json` of the library.

```
var packageJson = require('../../package.json');
// ...

Rollbar.defaultOptions = {
  // ...
  scrubHeaders: packageJson.defaults.server.scrubHeaders,
  scrubFields: packageJson.defaults.server.scrubFields,
  // ...
};

module.exports = Rollbar;
```

It appears as if baseUrl is causing an issue with json files imports (at least within node_modules possibly more extensively than that).

here is a repo with a quick reproduction.

https://github.com/charlesdeuter/bug-example-ncc

**Comment by TimPchelintsev** [comment]
Hi! I think my issue can be related to this one. I use npm package `"country-state-city-js": "^2.5.0"` and it's working with npm run dev and npm build & npm start locally. But in vercel deployment I get `Error: Cannot find module '/var/task/node_modules/country-state-city-js/db/countries/AD/index.json'`.

**Comment by dr2009** [comment]
same! +1

babel-loader with tsconfig.json baseUrl:"." 
output`s babel-loader package.json will be my project`s package.json

**Comment by fiws** [comment]
i think i had the same problem and fixed it in https://github.com/vercel/ncc/pull/987 

it's merged but still not released. you could try the main branch to confirm
