### ISSUE TITLE
TypeORM entity mapping not working

### ISSUE THREAD

**Issue by xtremebiker** [vercel/ncc#909]
I'm compiling my NestJS 8 based project which uses TypeORM for database management. With ncc 0.33.3 this is the command I use to build it: `ncc build src/main.ts -o dist/
`
This is my tsconfig.json file at the root of my project:

```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "allowJs": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "esModuleInterop": true,
    "lib": ["es2017", "dom", "esnext"]
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}

```

The build finishes properly, however when I try to launch it with `cd dist && NODE_ENV=PRODUCTION TYPEORM_DATABASE=../database.sqlite node index.js` I have the error:

```
[Nest] 14956  - 2022/04/01 22:39:53     LOG [NestFactory] Starting Nest application...
[Nest] 14956  - 2022/04/01 22:39:53     LOG [InstanceLoader] AppModule dependencies initialized +83ms
[Nest] 14956  - 2022/04/01 22:39:53     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 14956  - 2022/04/01 22:39:53     LOG [InstanceLoader] CoreModule dependencies initialized +0ms
[Nest] 14956  - 2022/04/01 22:39:53     LOG [InstanceLoader] MediaModule dependencies initialized +0ms
[Nest] 14956  - 2022/04/01 22:39:53     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +390ms
[Nest] 14956  - 2022/04/01 22:39:53   ERROR [ExceptionHandler] No repository for "People" was found. Looks like this entity is not registered in current "default" connection?
RepositoryNotFoundError: No repository for "People" was found. Looks like this entity is not registered in current "default" connection?
    at RepositoryNotFoundError.TypeORMError [as constructor] (/home/user/projects/NEST_PROJECT/dist/index.js:275765:28)
    at new RepositoryNotFoundError (/home/user/projects/NEST_PROJECT/dist/index.js:193579:28)
    at EntityManager.module.exports.EntityManager.getRepository (/home/user/projects/NEST_PROJECT/dist/index.js:142790:19)
    at Connection.module.exports.Connection.getRepository (/home/user/projects/NEST_PROJECT/dist/index.js:165556:29)
    at InstanceWrapper.useFactory [as metatype] (/home/user/projects/NEST_PROJECT/dist/index.js:165972:30)
    at Injector.instantiateClass (/home/user/projects/NEST_PROJECT/dist/index.js:146644:55)
    at callback (/home/user/projects/NEST_PROJECT/dist/index.js:146393:41)
    at async Injector.resolveConstructorParams (/home/user/projects/NEST_PROJECT/dist/index.js:146469:24)
    at async Injector.loadInstance (/home/user/projects/NEST_PROJECT/dist/index.js:146397:9)
    at async Injector.loadProvider (/home/user/projects/NEST_PROJECT/dist/index.js:146419:9)
```

And this is the ormconfig.js I place at the same level of index.js (I point the entities search path to index too, since I believe the entities are wrapped there):

```
module.exports = {
  name: 'default',
  type: 'sqlite',
  database: process.env.TYPEORM_DATABASE ? process.env.TYPEORM_DATABASE : '/usr/local/database/database.sqlite',
  synchronize: false,
  logging: 'error',
  migrationsRun: false,
  entities: [
    __dirname + 'index.js',
  ],
};
```

The index.js also seems to include the People entity related code:

```
Object.defineProperty(exports, "__esModule", ({ value: true }));
exports.PeopleService = void 0;
const common_1 = __nccwpck_require__(31888);
const typeorm_1 = __nccwpck_require__(11564);
const rxjs_1 = __nccwpck_require__(51799);
const operators_1 = __nccwpck_require__(72618);
const typeorm_2 = __nccwpck_require__(735);
const shared_constants_1 = __nccwpck_require__(22265);
const people_entity_1 = __nccwpck_require__(16789);
let PeopleService = class PeopleService {
    constructor(repository) {
        this.repository = repository;
    }
    findAll() {
        return rxjs_1.from(this.repository.find({ where: [] }));
    }
};
```

Of course, the application runs perfectly well when no being packed with ncc.

**Comment by xtremebiker** [comment]
What worked for me in the end was to switch from the ormconfig file to using explicit imports. You need to import the entities one by one, but this does the work!

```
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { People } from './people/model/people.entity';

@Module({
  imports: [
    TypeOrmModule.forRoot({
      name: 'default',
      type: 'sqlite',
      database: process.env.TYPEORM_DATABASE ? process.env.TYPEORM_DATABASE : '/usr/local/database/database.sqlite',
      synchronize: false,
      logging: ['error'],
      migrationsRun: false,
      entities: [People],
    }),
  ],
})
export class DatabaseModule { }
```

**Comment by ElodieC** [comment]
Thank you for the solution it works ! I don't know if it's the best solution since you have to import all entities. I hope someone will have a better idea.
